/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uscs33_project.component;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import uscs33_project.event.LeftPanelFilter;

/**
 *
 * @author iyasnaufalnazlim
 */
public class BrowseFilter extends javax.swing.JPanel {

    /**
     * Creates new form BrowseFilter
     */
    
    private LeftPanelFilter eventFilter;
    
    public BrowseFilter(LeftPanelFilter event) {
        this.eventFilter = event;
        
        initComponents();
        allProducts.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(SwingUtilities.isLeftMouseButton(e))
                    eventFilter.filterBy("ID", "");
            }
        });
//        faceLabel.addMouseListener(new MouseAdapter() {
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                if(SwingUtilities.isLeftMouseButton(e))
//                    eventFilter.filterBy("ID", "F");
//            }
//        });
//        eyesLabel.addMouseListener(new MouseAdapter() {
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                if(SwingUtilities.isLeftMouseButton(e))
//                    eventFilter.filterBy("ID", "E");
//            }
//        });
//        lipsLabel.addMouseListener(new MouseAdapter() {
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                if(SwingUtilities.isLeftMouseButton(e))
//                    eventFilter.filterBy("ID", "L");
//            }
//        });
        
        for (Component com : jPanel1.getComponents()) {
            if (com instanceof JLabel label) {
                String idType = Character.toString(label.getText().charAt(0));
                label.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                    if(SwingUtilities.isLeftMouseButton(e))
                        eventFilter.filterBy("ID", idType.toLowerCase());
                    }
                });
            }
        }
        
        for (Component com : jPanel2.getComponents()) {
            if (com instanceof JLabel label) {
                String brand = label.getText();
                label.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                    if(SwingUtilities.isLeftMouseButton(e))
                        eventFilter.filterBy("Brand", brand.toLowerCase());
                    }
                });
            }
        }
    }
    
    public BrowseFilter() { 
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        makeupTitle = new javax.swing.JLabel();
        faceLabel = new javax.swing.JLabel();
        eyesLabel = new javax.swing.JLabel();
        lipsLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        makeupTitle1 = new javax.swing.JLabel();
        brandLabel1 = new javax.swing.JLabel();
        brandLabel2 = new javax.swing.JLabel();
        brandLabel3 = new javax.swing.JLabel();
        brandLabel4 = new javax.swing.JLabel();
        brandLabel5 = new javax.swing.JLabel();
        brandLabel6 = new javax.swing.JLabel();
        brandLabel7 = new javax.swing.JLabel();
        brandLabel8 = new javax.swing.JLabel();
        brandLabel9 = new javax.swing.JLabel();
        brandLabel10 = new javax.swing.JLabel();
        brandLabel14 = new javax.swing.JLabel();
        brandLabel15 = new javax.swing.JLabel();
        brandLabel16 = new javax.swing.JLabel();
        brandLabel17 = new javax.swing.JLabel();
        brandLabel18 = new javax.swing.JLabel();
        brandLabel19 = new javax.swing.JLabel();
        allProducts = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(250, 750));

        jPanel1.setOpaque(false);

        makeupTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        makeupTitle.setText("M A K E  U P");

        faceLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        faceLabel.setText("FACE");
        faceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                faceLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                faceLabelMouseExited(evt);
            }
        });

        eyesLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        eyesLabel.setText("EYES");
        eyesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eyesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eyesLabelMouseExited(evt);
            }
        });

        lipsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lipsLabel.setText("LIPS");
        lipsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lipsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lipsLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(makeupTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lipsLabel)
                    .addComponent(eyesLabel)
                    .addComponent(faceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeupTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eyesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lipsLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setOpaque(false);

        makeupTitle1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        makeupTitle1.setText("B R A N D");

        brandLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel1.setText("RARE BEAUTY");
        brandLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel1MouseExited(evt);
            }
        });

        brandLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel2.setText("TARTE");
        brandLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel2MouseExited(evt);
            }
        });

        brandLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel3.setText("HUDA BEAUTY");
        brandLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel3MouseExited(evt);
            }
        });

        brandLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel4.setText("MAC");
        brandLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel4MouseExited(evt);
            }
        });

        brandLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel5.setText("ESTÉE LAUDER");
        brandLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel5MouseExited(evt);
            }
        });

        brandLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel6.setText("ONE SIZE");
        brandLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel6MouseExited(evt);
            }
        });

        brandLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel7.setText("DIOR");
        brandLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel7MouseExited(evt);
            }
        });

        brandLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel8.setText("KÉRASTASE");
        brandLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel8MouseExited(evt);
            }
        });

        brandLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel9.setText("KYLIE");
        brandLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel9MouseExited(evt);
            }
        });

        brandLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel10.setText("CHRISTOPHE R");
        brandLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel10MouseExited(evt);
            }
        });

        brandLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel14.setText("COCO & EVE");
        brandLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel14MouseExited(evt);
            }
        });

        brandLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel15.setText("ARMANI");
        brandLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel15MouseExited(evt);
            }
        });

        brandLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel16.setText("GLOW RECIPE");
        brandLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel16MouseExited(evt);
            }
        });

        brandLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel17.setText("LANEIGE");
        brandLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel17MouseExited(evt);
            }
        });

        brandLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel18.setText("CLINIQUE");
        brandLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel18MouseExited(evt);
            }
        });

        brandLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        brandLabel19.setText("THE ORDINARY");
        brandLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brandLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandLabel19MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(makeupTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLabel7)
                            .addComponent(brandLabel6)
                            .addComponent(brandLabel2)
                            .addComponent(brandLabel4)
                            .addComponent(brandLabel5)
                            .addComponent(brandLabel3)
                            .addComponent(brandLabel1))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLabel19)
                            .addComponent(brandLabel18)
                            .addComponent(brandLabel17)
                            .addComponent(brandLabel16)
                            .addComponent(brandLabel15)
                            .addComponent(brandLabel14)
                            .addComponent(brandLabel10)
                            .addComponent(brandLabel9)
                            .addComponent(brandLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeupTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(brandLabel19)
                .addGap(78, 78, 78))
        );

        allProducts.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        allProducts.setText("A L L");
        allProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allProductsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(allProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(allProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void faceLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faceLabelMouseEntered
        faceLabel.setForeground(new Color(255,102,102));     
    }//GEN-LAST:event_faceLabelMouseEntered

    private void faceLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faceLabelMouseExited
        faceLabel.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_faceLabelMouseExited

    private void eyesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyesLabelMouseEntered
        eyesLabel.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_eyesLabelMouseEntered

    private void eyesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyesLabelMouseExited
        eyesLabel.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_eyesLabelMouseExited

    private void lipsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lipsLabelMouseEntered
        lipsLabel.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_lipsLabelMouseEntered

    private void lipsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lipsLabelMouseExited
        lipsLabel.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_lipsLabelMouseExited

    private void brandLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel1MouseEntered
        brandLabel1.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel1MouseEntered

    private void brandLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel1MouseExited
        brandLabel1.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel1MouseExited

    private void brandLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel2MouseEntered
        brandLabel2.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel2MouseEntered

    private void brandLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel2MouseExited
        brandLabel2.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel2MouseExited

    private void brandLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel3MouseEntered
        brandLabel3.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel3MouseEntered

    private void brandLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel3MouseExited
        brandLabel3.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel3MouseExited

    private void brandLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel4MouseEntered
        brandLabel4.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel4MouseEntered

    private void brandLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel4MouseExited
        brandLabel4.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel4MouseExited

    private void brandLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel5MouseEntered
        brandLabel5.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel5MouseEntered

    private void brandLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel5MouseExited
        brandLabel5.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel5MouseExited

    private void brandLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel6MouseEntered
        brandLabel6.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel6MouseEntered

    private void brandLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel6MouseExited
        brandLabel6.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel6MouseExited

    private void allProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allProductsMouseEntered
        allProducts.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_allProductsMouseEntered

    private void allProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allProductsMouseExited
        allProducts.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_allProductsMouseExited

    private void brandLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel7MouseEntered
        brandLabel6.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel7MouseEntered

    private void brandLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel7MouseExited
        brandLabel7.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel7MouseExited

    private void brandLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel8MouseEntered
        brandLabel8.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel8MouseEntered

    private void brandLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel8MouseExited
        brandLabel8.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel8MouseExited

    private void brandLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel9MouseEntered
        brandLabel9.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel9MouseEntered

    private void brandLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel9MouseExited
        brandLabel9.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel9MouseExited

    private void brandLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel10MouseEntered
        brandLabel10.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_brandLabel10MouseEntered

    private void brandLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel10MouseExited
       brandLabel10.setForeground(new Color(0,0,0)); // TODO add your handling code here:
    }//GEN-LAST:event_brandLabel10MouseExited

    private void brandLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel14MouseEntered
        brandLabel14.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_brandLabel14MouseEntered

    private void brandLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel14MouseExited
        brandLabel14.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_brandLabel14MouseExited

    private void brandLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel15MouseEntered
        brandLabel15.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_brandLabel15MouseEntered

    private void brandLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel15MouseExited
        brandLabel15.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_brandLabel15MouseExited

    private void brandLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel16MouseEntered
        brandLabel16.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_brandLabel16MouseEntered

    private void brandLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel16MouseExited
        brandLabel16.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_brandLabel16MouseExited

    private void brandLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel17MouseEntered
        brandLabel17.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_brandLabel17MouseEntered

    private void brandLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel17MouseExited
        brandLabel17.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_brandLabel17MouseExited

    private void brandLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel18MouseEntered
       brandLabel18.setForeground(new Color(255,102,102)); 
    }//GEN-LAST:event_brandLabel18MouseEntered

    private void brandLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel18MouseExited
       brandLabel18.setForeground(new Color(0,0,0)); 
    }//GEN-LAST:event_brandLabel18MouseExited

    private void brandLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel19MouseEntered
        brandLabel19.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_brandLabel19MouseEntered

    private void brandLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandLabel19MouseExited
        brandLabel19.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_brandLabel19MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allProducts;
    private javax.swing.JLabel brandLabel1;
    private javax.swing.JLabel brandLabel10;
    private javax.swing.JLabel brandLabel14;
    private javax.swing.JLabel brandLabel15;
    private javax.swing.JLabel brandLabel16;
    private javax.swing.JLabel brandLabel17;
    private javax.swing.JLabel brandLabel18;
    private javax.swing.JLabel brandLabel19;
    private javax.swing.JLabel brandLabel2;
    private javax.swing.JLabel brandLabel3;
    private javax.swing.JLabel brandLabel4;
    private javax.swing.JLabel brandLabel5;
    private javax.swing.JLabel brandLabel6;
    private javax.swing.JLabel brandLabel7;
    private javax.swing.JLabel brandLabel8;
    private javax.swing.JLabel brandLabel9;
    private javax.swing.JLabel eyesLabel;
    private javax.swing.JLabel faceLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lipsLabel;
    private javax.swing.JLabel makeupTitle;
    private javax.swing.JLabel makeupTitle1;
    // End of variables declaration//GEN-END:variables
}
