/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uscs33_project.component;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


/**
 *
 * @author iyasnaufalnazlim
 */
public class promoBanner extends javax.swing.JPanel {
    
    /**
     * Creates new form promoBanner
     */
    
    
    String icon1 = "/uscs33_project/promo_pics/1.png";
    String icon2 = "/uscs33_project/promo_pics/2.png";
    String icon3 = "/uscs33_project/promo_pics/3.png";
    String icon4 = "/uscs33_project/promo_pics/4.png";
    String icon5 = "/uscs33_project/promo_pics/5.png";
    
    String[] promoImages = {icon1, icon2, icon3, icon4, icon5};
    private int index = 0;
    
    
      
    public promoBanner() {
        initComponents();
        Timer timer = new Timer(3000, new ActionListener(){
            public void actionPerformed(ActionEvent e){
                index = (index + 1) % promoImages.length;
                updateImage();
            }
        });
        
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theBanner = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void updateImage(){
        ImageIcon currentIcon = new ImageIcon(getClass().getResource(promoImages[index]));
        theBanner.setIcon(currentIcon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel theBanner;
    // End of variables declaration//GEN-END:variables
}
