/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uscs33_project.component;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author iyasnaufalnazlim
 */
public class searchFeature extends javax.swing.JFrame {

    public JTextField searchField;
    public JList<String> searchResult;
    public JScrollPane scrollPane;
    public DefaultListModel<String> listModel;
    
    //SAMPLE DATA
    
    public List<String> data = List.of(
            "rare beauty", "huda beauty", "estee launder",
            "tarte", "one size", "mac");
    
    //SAMPLE DATA
    
    public searchFeature() {
        initComponents();
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        searchField = new JTextField();
        listModel = new DefaultListModel<>();
        searchResult = new JList<>(listModel);
        scrollPane = new JScrollPane(searchResult);
        scrollPane.setPreferredSize(new Dimension (454, 100));
        scrollPane.setVisible(false);
        
        searchField.getDocument().addDocumentListener(new DocumentListener() {
        
            @Override
            public void insertUpdate(DocumentEvent e){
                updateSearchResults();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e){
                updateSearchResults();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e){
                updateSearchResults();
            }
                        
        
        });
        
        searchResult.addMouseListener(new MouseAdapter(){
        
            public void mouseClicked(MouseEvent evt){
                if(evt.getClickCount() == 1){
                    searchField.setText(searchResult.getSelectedValue());
                    scrollPane.setVisible(false);
                }
            }
            
        });
        
        setVisible(true);
        
        jPanel1.add(searchField, BorderLayout.NORTH);
        jPanel1.add(scrollPane, BorderLayout.CENTER);
        
        jPanel1.setVisible(true);
        
        
        
              
    }
    
    
    private void updateSearchResults(){
        String searchText = searchField.getText().toLowerCase();
        listModel.clear();
        
        if(searchText.isEmpty()){
        
            scrollPane.setVisible(false);
            return;
        
        }
        
        List<String> filtered = new ArrayList<>();
        for(String item : data){
            if(item.toLowerCase().contains(searchText)){
                filtered.add(item);
            }
        }
        
        if(!filtered.isEmpty()){
            for(String item : filtered){
                listModel.addElement(item);
            }
            scrollPane.setVisible(true);
        }
        else{
            scrollPane.setVisible(false);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        SwingUtilities.invokeLater(() -> new searchFeature());
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
