/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uscs33_project.form;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import javax.swing.border.TitledBorder;
import uscs33_project.model.ModelItemChoice;
import uscs33_project.form.ShoppingCart;



/**
 *
 * @author iyasnaufalnazlim
 */
public class FormReceipt extends javax.swing.JFrame {
    
    private static final double TAX_RATE = 0.06;       // 6% tax
    private static final double SHIPPING_FEE = 7.00;   // Flat rate
    
    public FormReceipt(ArrayList<ModelItemChoice> items, String username, String[] address, String subz){
        setTitle("Receipt");
        setSize(500, 600);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout(10, 10));

        // ========== HEADER PANEL ==========
        JPanel headerPanel = new JPanel();
        headerPanel.setLayout(new BoxLayout(headerPanel, BoxLayout.Y_AXIS));
        headerPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "MAKLUV", TitledBorder.CENTER, TitledBorder.TOP));
        headerPanel.add(new JLabel("To:"));
        headerPanel.add(new JLabel(username));
        for (String line : address) {
            headerPanel.add(new JLabel(line));
        }

        // ========== TEXT AREA FOR ITEMS ==========
        JTextArea receiptArea = new JTextArea();
        receiptArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        receiptArea.setEditable(false);
        receiptArea.setText(buildReceiptContent(items));

        JScrollPane scrollPane = new JScrollPane(receiptArea);
        scrollPane.setBorder(BorderFactory.createTitledBorder("Items"));

        // ========== FOOTER PANEL ==========
        JPanel footerPanel = new JPanel();
        footerPanel.setLayout(new BoxLayout(footerPanel, BoxLayout.Y_AXIS));
        footerPanel.setBorder(BorderFactory.createTitledBorder("Thank You!"));
        
        
        double subtotal = Double.parseDouble(subz);
        double tax = subtotal * TAX_RATE;
        double total = subtotal + tax + SHIPPING_FEE;
        
        
        JPanel contentPanel = new JPanel(new GridLayout(0, 1));
        footerPanel.add(new JLabel(String.format("Subtotal:     $%.2f", subtotal)));
        footerPanel.add(new JLabel(String.format("Tax (6%%):     $%.2f", tax)));
        footerPanel.add(new JLabel(String.format("Shipping Fee: $%.2f", SHIPPING_FEE)));
        footerPanel.add(new JLabel(String.format("TOTAL:        $%.2f", total)));
        
        // ========== ADD COMPONENTS TO FRAME ==========
        add(headerPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
        add(footerPanel, BorderLayout.SOUTH);

        setVisible(true);
              
        
    }
    
    
    private String buildReceiptContent(ArrayList<ModelItemChoice> items) {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("%-40s %10s\n", "ITEM", "PRICE"));
        sb.append("\n");

        for (ModelItemChoice item : items) {
            String name = item.getItemName();
            if (name.length() > 40) {
                name = name.substring(0, 37) + "...";
            }
            sb.append(String.format("%-40s %10s\n", name, String.format("$%.2f", item.getPrice())));
        }

        return sb.toString();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
