/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uscs33_project.form;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import uscs33_project.model.ModelItemChoice;

/**
 *
 * @author USER
 */

public class ShoppingCart extends javax.swing.JFrame {

    public ArrayList<ArrayList<String>> product = new ArrayList<ArrayList<String>>();
    public ArrayList<JSpinner> SpinnerList = new ArrayList<JSpinner>();
    public JLabel SubTotalLabel = new JLabel();
    public JLabel TaxLabel = new JLabel();
    public double stotal;
    public double stax;
    public double SubTotal;
    
    public ShoppingCart(ArrayList<ArrayList<String>> product) {
        this.product = product; 
        this.QuantitySpinner = new ArrayList<>();
        initComponents();
        int y = 0;
        for (int i = 0; i < product.size();i++){
            addProductPanel(i,y);
            y += 150;
        }
        Additional();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        MiddlePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ItemLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        QuantityLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CartPanel = new javax.swing.JPanel();
        ProductPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("cart");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setFocusCycleRoot(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 750));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MiddlePanel.setBackground(new java.awt.Color(255, 255, 255));
        MiddlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MiddlePanel.setPreferredSize(new java.awt.Dimension(1190, 750));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        ItemLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ItemLabel.setText("Item");

        PriceLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        PriceLabel.setText("Price");

        TotalLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        TotalLabel.setText("Total");

        QuantityLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        QuantityLabel.setText("Quantity");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(870, 750));

        CartPanel.setBackground(new java.awt.Color(255, 255, 255));
        CartPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CartPanel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CartPanel.setPreferredSize(new java.awt.Dimension(870, 750));

        javax.swing.GroupLayout CartPanelLayout = new javax.swing.GroupLayout(CartPanel);
        CartPanel.setLayout(CartPanelLayout);
        CartPanelLayout.setHorizontalGroup(
            CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        CartPanelLayout.setVerticalGroup(
            CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(CartPanel);

        ProductPanel.setBackground(new java.awt.Color(255, 255, 255));
        ProductPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Tax (10%)");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Subtotal");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("TOTAL");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("ORDER SUMMARY");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Shipping Fee");

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setText("CHECKOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("PAYMENT METHOD");

        javax.swing.GroupLayout MiddlePanelLayout = new javax.swing.GroupLayout(MiddlePanel);
        MiddlePanel.setLayout(MiddlePanelLayout);
        MiddlePanelLayout.setHorizontalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiddlePanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(ProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MiddlePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap())
        );
        MiddlePanelLayout.setVerticalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiddlePanelLayout.createSequentialGroup()
                        .addComponent(ProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MiddlePanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MiddlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JOptionPane.showMessageDialog(null, "You Successfully Ordered!");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void Additional(){
       
        SubTotalLabel.setBounds(180, 50, 60, 20);
        SubTotalLabel.setFont(new Font("Verdana",Font.PLAIN,12));
        //SubTotalLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        
        TaxLabel.setBounds(180, 90, 60, 20);
        TaxLabel.setFont(new Font("Verdana",Font.PLAIN,12));
       // TaxLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        TotalLabel.setBounds(180, 155, 60, 20);
        TotalLabel.setFont(new Font("Verdana",Font.BOLD,14));
       // TotalLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        JLabel ShippingLabel = new JLabel();
        ShippingLabel.setBounds(180, 120, 60, 20);
        ShippingLabel.setFont(new Font("Verdana",Font.PLAIN,12));
        //ShippingLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ShippingLabel.setText("7.00");
        
        
        ProductPanel.add(TaxLabel);
        ProductPanel.add(SubTotalLabel);
        ProductPanel.add(ShippingLabel);
        ProductPanel.add(TotalLabel);
    }
        

      private void addProductPanel(int itemIndex,int y){
        
        JPanel itemPanel = new JPanel();
        itemPanel.setBackground(Color.WHITE);
        itemPanel.setBorder(BorderFactory.createEtchedBorder());
        //itemPanel.setPreferredSize(new Dimension(300, 600));
        itemPanel.setLayout(null); // Use absolute layout for simplicity (or use GroupLayout if preferred)
        JLabel brandLabel = new JLabel(product.get(itemIndex).get(0));
        brandLabel.setBounds(20, 20, 300, 20);
        brandLabel.setFont(new Font("Verdana",Font.BOLD,12));
        //brandLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel nameLabel = new JLabel(product.get(itemIndex).get(1));
        nameLabel.setBounds(20, 45, 300, 20);
        nameLabel.setFont(new Font("Verdana",Font.PLAIN,12));
        //nameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel detailLabel = new JLabel(product.get(itemIndex).get(2));
        detailLabel.setBounds(20, 70, 300, 20);
        detailLabel.setFont(new Font("Verdana",Font.PLAIN,12));
        //detailLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel priceLabel = new JLabel(product.get(itemIndex).get(3));
        priceLabel.setBounds(350, 20, 60, 20);
        priceLabel.setFont(new Font("Verdana",Font.PLAIN,12));
        //priceLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLabel totalLabel = new JLabel(product.get(itemIndex).get(3));
        totalLabel.setBounds(670, 20, 60, 20);
        totalLabel.setFont(new Font("Verdana",Font.PLAIN,12));
        //totalLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
    
        SpinnerList.add(new JSpinner(new SpinnerNumberModel(1, 1, 100, 1)));
        JSpinner spinner = SpinnerList.get(itemIndex);
        spinner.setBounds(530, 20, 60, 25);
        
        
        stotal += Double.parseDouble(product.get(itemIndex).get(3));
        SubTotalLabel.setText(String.format("%.2f",stotal));
        
        stax = (0.06 * stotal);
        TaxLabel.setText(String.format("%.2f",stax));
        
        double total = stotal + stax;
        TotalLabel.setText(String.format("%.2f",total));
        
        double Shipping = 7.00;
        
        
        
    // Add change listener to update ttal
        spinner.addChangeListener(new ChangeListener() {
        public void stateChanged(ChangeEvent e) {
            int quantity = (int) spinner.getValue();
            double price = Double.parseDouble(product.get(itemIndex).get(3));
            double total = quantity * price;
            totalLabel.setText(String.format("%.2f", total));
            
            double SubTotal = 0;
            double tax = 0;
            double Total = 0;
            for(int i = 0; i < product.size();i++){
                int quantitySub = (Integer) SpinnerList.get(i).getValue();
                double priceSub = Double.parseDouble(product.get(i).get(3));
                SubTotal += (priceSub*quantitySub);
                
            }
            tax = SubTotal * 0.06;
            Total = SubTotal + tax + Shipping;
            TaxLabel.setText(String.format("%.2f",tax));
            SubTotalLabel.setText(String.format("%.2f",SubTotal));
            TotalLabel.setText(String.format("%.2f",Total));
            SubTotalLabel.revalidate();
            SubTotalLabel.repaint();
            TaxLabel.revalidate();
            TaxLabel.repaint();
            TotalLabel.revalidate();
            TotalLabel.repaint();

        }
    });
    itemPanel.setBounds(0, y, 870, 140);
   

    JButton editButton = new JButton("Edit");
    editButton.setBounds(750,40,80,25);
    editButton.addActionListener(e ->{
        String newDetail = JOptionPane.showInputDialog(itemPanel,"Edit Details: ", detailLabel.getText());
        if (newDetail != null & !newDetail.trim().isEmpty()){
            detailLabel.setText(newDetail);
        }
   
    });
    
     
     JButton deleteButton = new JButton("Delete");
    deleteButton.setBounds(750,70,80,25);
    deleteButton.addActionListener(e -> {
        int result = JOptionPane.showConfirmDialog(ItemPanel, "Are you sure to delete the product?", "Delete Item",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
            CartPanel.remove(itemPanel);
            CartPanel.revalidate();
            CartPanel.repaint();
            int indexToRemove = (int) ((JButton) e.getSource()).getClientProperty("itemIndex");
            if (indexToRemove >= 0 && indexToRemove < product.size()) {
                product.remove(indexToRemove);
                SpinnerList.remove(indexToRemove); // Also remove from SpinnerList if needed
                
            }
            
        }
    });
    

    itemPanel.add(brandLabel);
    itemPanel.add(nameLabel);
    itemPanel.add(detailLabel);
    itemPanel.add(priceLabel);
    itemPanel.add(spinner);
    itemPanel.add(totalLabel);
    itemPanel.add(editButton);
    itemPanel.add(deleteButton);
    
    CartPanel.add(itemPanel);
    CartPanel.revalidate();
    CartPanel.repaint();
    
}
    public JPanel getPanel(){
        return MiddlePanel;
    }
      
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<ArrayList<String>> product = new ArrayList<ArrayList<String>>();
                ArrayList<String> item = new ArrayList<String>();
                item.add("Fenty Beauty");
                item.add("Gloss Bomb");
                item.add("Champ Color");
                item.add("79.00");
                product.add(new ArrayList<>(item));
                item.clear();
                item.add("Dior");
                item.add("Matte Blusher");
                item.add("Lovely Pink");
                item.add("59.00");
                product.add(new ArrayList<>(item));
                item.clear();
                item.add("Dior");
                item.add("Lipstick Glaze");
                item.add("Charmer Nude");
                item.add("69.00");
                product.add(new ArrayList<>(item));
                new ShoppingCart(product).setVisible(true);
                
                
            }
       });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel CartPanel;
    public javax.swing.JLabel ItemLabel;
    public javax.swing.JPanel MiddlePanel;
    public javax.swing.JLabel PriceLabel;
    public javax.swing.JPanel ProductPanel;
    public javax.swing.JLabel QuantityLabel;
    public javax.swing.JLabel TotalLabel;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JLabel BrandText;
    public javax.swing.JButton DeleteButton;
    public javax.swing.JLabel Detailtext;
    public javax.swing.JButton EditButton;
    public javax.swing.JPanel ItemPanel;
    public javax.swing.JLabel NameText;
    public javax.swing.JLabel PriceText;
    public javax.swing.JLabel[] Totaltext;
    public ArrayList<javax.swing.JSpinner> QuantitySpinner;
    }
