/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uscs33_project;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author iyasnaufalnazlim
 */
public class BrowseFilter extends javax.swing.JPanel {

    /**
     * Creates new form BrowseFilter
     */
    public BrowseFilter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        makeupTitle = new javax.swing.JLabel();
        faceLabel = new javax.swing.JLabel();
        eyesLabel = new javax.swing.JLabel();
        lipsLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(250, 750));

        jPanel1.setOpaque(false);

        makeupTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        makeupTitle.setText("M A K E  U P");

        faceLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        faceLabel.setText("FACE");
        faceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                faceLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                faceLabelMouseExited(evt);
            }
        });

        eyesLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        eyesLabel.setText("EYES");
        eyesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eyesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eyesLabelMouseExited(evt);
            }
        });

        lipsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lipsLabel.setText("LIPS");
        lipsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lipsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lipsLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(makeupTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lipsLabel)
                    .addComponent(eyesLabel)
                    .addComponent(faceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeupTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eyesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lipsLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(580, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void faceLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faceLabelMouseEntered
        faceLabel.setForeground(new Color(255,102,102));     // TODO add your handling code here:
    }//GEN-LAST:event_faceLabelMouseEntered

    private void faceLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faceLabelMouseExited
        faceLabel.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_faceLabelMouseExited

    private void eyesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyesLabelMouseEntered
        eyesLabel.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_eyesLabelMouseEntered

    private void eyesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyesLabelMouseExited
        eyesLabel.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_eyesLabelMouseExited

    private void lipsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lipsLabelMouseEntered
        lipsLabel.setForeground(new Color(255,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_lipsLabelMouseEntered

    private void lipsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lipsLabelMouseExited
        lipsLabel.setForeground(new Color(0,0,0));// TODO add your handling code here:
    }//GEN-LAST:event_lipsLabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eyesLabel;
    private javax.swing.JLabel faceLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lipsLabel;
    private javax.swing.JLabel makeupTitle;
    // End of variables declaration//GEN-END:variables
}
